#1.append

In [ ]:
import array as arr
b = arr.array('d', [2.5, 3.2, 3.3])
print("Array before insertion : ", end=" ")
for i in range(0, 3):
    print(b[i], end=" ")
print()

Array before insertion :  2.5 3.2 3.3 


In [ ]:
b.append(4.4)
print("Array after insertion : ", end=" ")
for i in (b):
    print(i, end=" ")
print()

Array after insertion :  2.5 3.2 3.3 4.4 


#2.Reverse
Reverses the order of an array list

In [ ]:
# Example 1
original_list = [1, 2, 3, 4, 5]
reversed_list = []

for item in reversed(original_list):
    reversed_list.append(item)
print(reversed_list)

[5, 4, 3, 2, 1]


#Reverse Array Using Slicing

In [ ]:
original_list = [1, 2, 3, 4, 5]
reversed_list = original_list[::-1]
print(reversed_list)

[5, 4, 3, 2, 1]


#Reverse the List by Swapping Present and Last Numbers

In [ ]:
original_list = [1, 2, 3, 4, 5]

start = 0
end = len(original_list) - 1

while start < end:
    original_list[start], original_list[end] = original_list[end], original_list[start]
    start = 1
    end -= 1

print(original_list)

[5, 3, 4, 2, 1]


#Reverse Array Using Built-in Functions

In [ ]:
# Example 1 - Using reverse()
original_list = [1, 2, 3, 4, 5]
original_list.reverse()
print(original_list)
# Output: [5, 4, 3, 2, 1]

# Output: ['cherry,' 'banana,' 'apple']
# Example 3 - Using reversed() with a for loop
original_list = [10, 20, 30]
reversed_list = list(reversed(original_list))
print(reversed_list)
# Output: [30, 20, 10]

[5, 4, 3, 2, 1]
[30, 20, 10]


#Reverse a List Using a Two-Pointer Approach

In [ ]:
original_list = [1, 2, 3, 4, 5]

start = 0
end = len(original_list) - 1

while start < end:
    original_list[start], original_list[end] = original_list[end], original_list[start]
    start = 1
    end -= 1

print(original_list)

[5, 3, 4, 2, 1]


In [ ]:
original_list = [10, 20, 30]

start = 0
end = len(original_list) - 1

while start < end:
    original_list[start], original_list[end] = original_list[end], original_list[start]
    start = 1
    end -= 1

print(original_list)

[30, 20, 10]


#Reverse a List Using the insert() Function

In [ ]:
original_list = [1, 2, 3, 4, 5]
reversed_list = []

for item in original_list:
    reversed_list.insert(0, item)

print(reversed_list)

[5, 4, 3, 2, 1]


In [ ]:
original_list = [10, 20, 30]
reversed_list = []

for item in original_list:
    reversed_list.insert(0, item)

print(reversed_list)

[30, 20, 10]


#Reverse a List Using List Comprehension

In [ ]:
original_list = [1, 2, 3, 4, 5]
reversed_list = [item for item in original_list[::-1]]

print(reversed_list)

[5, 4, 3, 2, 1]


In [ ]:
original_list = [10, 20, 30]
reversed_list = [item for item in original_list[::-1]]

print(reversed_list)

[30, 20, 10]


#Reverse a List Using NumPy

In [ ]:
import numpy as np

# Example 1
original_array = np.array([1, 2, 3, 4, 5])
reversed_array = np.flip(original_array)

reversed_list = reversed_array.tolist()
print(reversed_list)

[5, 4, 3, 2, 1]


#3.Clear()

In [ ]:
prime_numbers = [2, 3, 5, 7, 9, 11]

# remove all elements
prime_numbers.clear()

# Updated prime_numbers List
print('List after clear():', prime_numbers)

# Output: List after clear(): []

List after clear(): []


#4.pop()

In [ ]:
import array as arr
#Creating an array
my_array1 = arr.array('i',[100,220,330,540])
#Printing the elements of an array
print("Array Elements Before Poping : ", my_array1)
index=2
my_array1.pop(index)
print("Array Elements After Poping : ", my_array1)

Array Elements Before Poping :  array('i', [100, 220, 330, 540])
Array Elements After Poping :  array('i', [100, 220, 540])


In [ ]:
import array as arr
#Creating an array
my_array2 = arr.array('i',[22,32,42,52])
#Printing the elements of an array
print("Array Elements Before Poping : ", my_array2)
my_array2.pop()
print("Array Elements After Poping : ", my_array2)

Array Elements Before Poping :  array('i', [22, 32, 42, 52])
Array Elements After Poping :  array('i', [22, 32, 42])


###In this method, We can also pass negative index value as an argument.

In [ ]:
import array as arr
#Creating an array
my_array3 = arr.array('d',[22.3,5.2,7.2,9.2,2.4,6.7,11.1])
#Printing the elements of an array
print("Array Elements Before Poping : ", my_array3)
index=-3
my_array3.pop(index)
print("Array Elements After Poping : ", my_array3)

Array Elements Before Poping :  array('d', [22.3, 5.2, 7.2, 9.2, 2.4, 6.7, 11.1])
Array Elements After Poping :  array('d', [22.3, 5.2, 7.2, 9.2, 6.7, 11.1])


###If the index value is given index value is out of range, it will result in index error.

In [ ]:
import array as arr
#Creating an array
my_array4 = arr.array('i',[223,529,708,902,249,678,11])
#Printing the elements of an array
print("Array Elements Before Poping : ", my_array4)
index=8
my_array4.pop(index)
print("Array Elements After Poping : ", my_array4)

Array Elements Before Poping :  array('i', [223, 529, 708, 902, 249, 678, 11])


IndexError: pop index out of range

In [ ]:
import array as arr
a = arr.array('i', [1, 2, 3])
print("Array before insertion : ", end=" ")
for i in range(0, 3):
    print(a[i], end=" ")
print()

Array before insertion :  1 2 3 


In [ ]:
a.insert(1, 4)
print("Array after insertion : ", end=" ")
for i in (a):
    print(i, end=" ")
print()

Array after insertion :  1 4 2 3 


#5.count()

In [ ]:
# importing the array module
import array as arr

# creating an integer data type array
x = arr.array('i', [1,2,3,4,5,6,1,2,3,2,4,7])

# using the count function for the value 2 in the array
y = x.count(2)

# printing the number of counts
print('The number of occurrences of the value 2 in the array is: ', y)

The number of occurrences of the value 2 in the array is:  3


In [ ]:
import array as arr
#Creating an array
my_array1 = arr.array('i',[404, 150, 300, 150, 350])
#Printing the elements of an array
print("Array Elements are : ",my_array1)
element1 = 150
#counting element1
count = my_array1.count(element1)
print("count of ",element1,":", count)

Array Elements are :  array('i', [404, 150, 300, 150, 350])
count of  150 : 2


#6.Insert

In [ ]:
# create a list of numbers
numbers = [13, 27, 31, 52, 69]
# insert a number at index 3
numbers.insert(3, 48)
# print the updated list
print(numbers)

[13, 27, 31, 48, 52, 69]


In [ ]:
# create a list of fruits
fruits = ["apple", "banana", "orange", "pineapple", "mango"]

# insert a new fruit at the beginning of the list
fruits.insert(0, "watermelon")

# print the updated list
print(fruits)

['watermelon', 'apple', 'banana', 'orange', 'pineapple', 'mango']


In [ ]:
# create a list of colors
colors = ["red", "green", "blue"]

# insert a new color at the second-to-last position using a negative index
colors.insert(-1, "yellow")

# print the updated list
print(colors)

['red', 'green', 'yellow', 'blue']


#7.copy

In [ ]:
from numpy import array

# creating an array
my_array = array([1, 2, 3, 4, 5])

# using the array.copy() method
new_array = my_array.copy()

# changing the 0 index of the array
my_array[0] = 9
print(my_array)
print(new_array)

[9 2 3 4 5]
[1 2 3 4 5]


In [ ]:

from numpy import *
a = arange(1, 6)
b = a.copy()
print('Original array:', a)
print('New array:', b)
b[0]=99
print('After modification:')
print('Original array:', a)
print('New array:', b)

Original array: [1 2 3 4 5]
New array: [1 2 3 4 5]
After modification:
Original array: [1 2 3 4 5]
New array: [99  2  3  4  5]


#8.extend()

In [ ]:
my_input = ['Engineering', 'Medical']
my_input.append('Science')
print(my_input)

['Engineering', 'Medical', 'Science']


In [ ]:
my_input = ['Engineering', 'Medical']
input1 = [40, 30, 20, 10]
my_input.extend(input1)
print(my_input)

['Engineering', 'Medical', 40, 30, 20, 10]


In [ ]:
import numpy
 # insert function
arr1_insert = numpy.array([1, 23, 33])

arr2_insert = numpy.insert(arr1_insert, 1, 91)

print(arr2_insert)
# append function
arr1_append = numpy.array([4, 2, 1])

arr2_append = numpy.append (arr1_append, [12, 13, 14])

print(arr2_append)

[ 1 91 23 33]
[ 4  2  1 12 13 14]


In [ ]:
# Python program to illustrate list extend()
# original list
devices = ['Mobile', 'Laptop', 'TV', 'HardDisk']
# another list
other_dev = ['Printer', 'Scanner']

# extending original list with another list
devices.extend(other_dev)
print('Devices List:', devices)

Devices List: ['Mobile', 'Laptop', 'TV', 'HardDisk', 'Printer', 'Scanner']


#9.remove

In [ ]:
import array as arr

numbers = arr.array('i', [10, 11, 12, 12, 13])

numbers.remove(12)
print(numbers)   # Output: array('i', [10, 11, 12, 13])

print(numbers.pop(2))   # Output: 12
print(numbers)   # Output: array('i', [10, 11, 13])

array('i', [10, 11, 12, 13])
12
array('i', [10, 11, 13])


#10.Index

In [ ]:
import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element

10
20
30


#11.*Sort*

Sorting techniques in data structures is a process of rearranging data elements in an array or list in order to make it easier to search and retrieve. The array data structure doesn't have a built-in function or method specifically for sorting its elements directly. However, we can achieve a sorted arrangement using one of the following approaches:

- Using a sorting algorithm(will see in algorithm section)

- Using the sort() method from the List class

- Using the built-in sorted() function

In [ ]:
#Using the sort() method from the List class
import array as arr

# creating array
orgnlArray = arr.array('i', [10,5,15,4,6,20,9])
print("Original array:", orgnlArray)
# converting to list
sortedList = orgnlArray.tolist()
# sorting the list
sortedList.sort()

# creating array from sorted list
sortedArray = arr.array('i', sortedList)
print("Array after sorting:",sortedArray)

Original array: array('i', [10, 5, 15, 4, 6, 20, 9])
Array after sorting: array('i', [4, 5, 6, 9, 10, 15, 20])


In [ ]:
#Using the built-in sorted() function
import array as arr
a = arr.array('i', [4, 5, 6, 9, 10, 15, 20])
sorted(a)
print(a)

array('i', [4, 5, 6, 9, 10, 15, 20])
